---
- name: Update Rocky Linux Servers - Starting Deployment
  hosts: rocky_linux_servers
  tasks:
    - name: DNF | Update System
      ansible.builtin.dnf:
        name: '*'
        state: latest
        update_cache: yes
- name: Update Debian Servers - Starting Deployment
  hosts: debian_servers
  tasks:
    - name: APT | Update System
      ansible.builtin.apt: name='*' state=latest