---
- name: Deploy de Infraestrutura Base
  hosts: homelab
  become: true
  roles:
    - nginx
  tasks:
    - name: Validar o Ansible Vault (NUNCA exiba senhas reais no terminal em prod!)
      ansible.builtin.debug:
        msg: "O Vault funcionou! O segredo e: {{ api_key_secreta }}"
