---
- name: Deploy de Servidor Web Nginx Dinamico
  hosts: homelab
  become: true

  tasks:
    - name: Instalar o servidor web Nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Garantir que o Nginx esta rodando e habilitado no boot
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: Definir diretorio base do Nginx baseado no Sistema Operacional
      ansible.builtin.set_fact:
        doc_root: "{{ '/var/www/html' if ansible_os_family == 'Debian' else '/usr/share/nginx/html' }}"

    - name: Deploy da pagina HTML customizada usando Jinja2
      ansible.builtin.template:
        src: ../templates/index.html.j2
        dest: "{{ doc_root }}/index.html"
        mode: '0644'
